In [3]:
import dgl
import torch

In [6]:
u, v = torch.tensor([0, 0, 0, 1]), torch.tensor([1, 2, 3, 3])
g = dgl.graph((u, v))
g

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [8]:
g.nodes()

tensor([0, 1, 2, 3])

In [9]:
g.edges()

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))

In [10]:
g.edges(form='all')

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))

In [11]:
g = dgl.graph((u,v),num_nodes=8)

In [13]:
bg = dgl.to_bidirected(g)

In [15]:
bg.edges()

(tensor([0, 0, 0, 1, 1, 2, 3, 3]), tensor([1, 2, 3, 0, 3, 0, 0, 1]))

In [17]:
edges = torch.tensor([2, 5, 3]), torch.tensor([3, 5, 0])

In [21]:
g64 = dgl.graph(edges,idtype=torch.int64)
g32 = dgl.graph(edges,idtype=torch.int32)

In [22]:
g64.idtype, g32.idtype

(torch.int64, torch.int32)

In [24]:
g64.int().idtype,g32.long().idtype

(torch.int32, torch.int64)