In [ ]:
import dgl,torch

In [ ]:
edges = (torch.tensor([0,0,1,5]),torch.tensor([1,2,2,0])) # 6 nodes,4 edges
g = dgl.graph(edges)
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

In [ ]:
g.ndata['x'] = torch.ones(size = (g.num_nodes(),3),dtype=torch.int32)
g.edata['x'] = torch.ones(size=(g.num_edges(),1),dtype=torch.int32)
g.ndata['x']

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [ ]:
g.edata['x']

tensor([[1],
        [1],
        [1],
        [1]], dtype=torch.int32)

In [ ]:
g.ndata['y'] = torch.randn(size=(g.num_nodes(), 5))

In [ ]:
g.ndata['y']

tensor([[ 0.3956, -0.7023,  0.1575, -0.7020,  0.9881],
        [ 1.8088,  0.8348,  1.7101, -1.7028,  0.0659],
        [-0.2208, -0.3977,  2.1991, -1.7100, -0.0972],
        [-0.5567, -0.3408,  0.1455,  0.3429,  0.0059],
        [-0.1976,  0.3107, -1.4978, -0.0548, -0.2230],
        [-1.5707, -0.3092, -1.5827, -0.3628, -0.8597]])

In [ ]:
g.ndata

{'x': tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32), 'y': tensor([[ 0.3956, -0.7023,  0.1575, -0.7020,  0.9881],
        [ 1.8088,  0.8348,  1.7101, -1.7028,  0.0659],
        [-0.2208, -0.3977,  2.1991, -1.7100, -0.0972],
        [-0.5567, -0.3408,  0.1455,  0.3429,  0.0059],
        [-0.1976,  0.3107, -1.4978, -0.0548, -0.2230],
        [-1.5707, -0.3092, -1.5827, -0.3628, -0.8597]])}

In [ ]:
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.int32), 'y': Scheme(shape=(5,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(1,), dtype=torch.int32)})

In [11]:
weights = torch.tensor([0.1, 0.6, 0.9, 0.7])

In [12]:
g.edata['w'] = weights

In [14]:
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.int32), 'y': Scheme(shape=(5,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(1,), dtype=torch.int32), 'w': Scheme(shape=(), dtype=torch.float32)})