In [1]:
import dgl
import torch

In [3]:
graph_data = {
    ('drug', 'interacts', 'drug'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('drug', 'interacts', 'gene'): (torch.tensor([0, 1]), torch.tensor([2, 3])),
    ('drug', 'treats', 'disease'): (torch.tensor([1]), torch.tensor([2]))
}

In [19]:
g = dgl.heterograph(graph_data)
g

Graph(num_nodes={'disease': 3, 'drug': 3, 'gene': 4},
      num_edges={('drug', 'interacts', 'drug'): 2, ('drug', 'interacts', 'gene'): 2, ('drug', 'treats', 'disease'): 1},
      metagraph=[('drug', 'drug', 'interacts'), ('drug', 'gene', 'interacts'), ('drug', 'disease', 'treats')])

In [25]:
g.num_nodes(),g.num_nodes('drug'),g.num_nodes('gene'),g.num_nodes('disease')

(10, 3, 4, 3)

In [35]:
g.num_edges(),g.num_edges(('drug', 'interacts', 'drug')),g.num_edges(('drug', 'interacts', 'gene')),g.num_edges(('drug', 'treats', 'disease'))

(5, 2, 2, 1)

In [36]:
g.nodes('drug'),g.nodes('gene'),g.nodes('disease')

(tensor([0, 1, 2]), tensor([0, 1, 2, 3]), tensor([0, 1, 2]))

In [59]:
g.nodes['drug'].data['hv'] = torch.rand(size=(g.num_nodes('drug'),3))
g.nodes['drug'].data['gv'] = torch.rand(size=(g.num_nodes('drug'),3))

In [60]:
g.nodes['drug'].data

{'hv': tensor([[0.0701],
        [0.8035],
        [0.9433]]), 'gv': tensor([[0.5141],
        [0.4337],
        [0.4275]])}

In [61]:
g.edges['treats'].data['he'] = torch.rand(size=(g.num_edges('treats'),3))
g.edges['treats'].data['ge'] = torch.rand(size=(g.num_edges('treats'),3))

In [62]:
g.edges['treats'].data

{'he': tensor([[0.6433, 0.7755, 0.4863]]), 'ge': tensor([[0.9074, 0.7671, 0.5597]])}

In [67]:
eg = dgl.edge_type_subgraph(g, [('drug', 'interacts', 'drug'),
                                ('drug', 'treats', 'disease')])

In [68]:
eg

Graph(num_nodes={'disease': 3, 'drug': 3},
      num_edges={('drug', 'interacts', 'drug'): 2, ('drug', 'treats', 'disease'): 1},
      metagraph=[('drug', 'drug', 'interacts'), ('drug', 'disease', 'treats')])

In [71]:
g = dgl.heterograph({
    ('drug', 'interacts', 'drug'): (torch.tensor([0, 1]), torch.tensor([1, 2])),
    ('drug', 'treats', 'disease'): (torch.tensor([1]), torch.tensor([2]))})
g

Graph(num_nodes={'disease': 3, 'drug': 3},
      num_edges={('drug', 'interacts', 'drug'): 2, ('drug', 'treats', 'disease'): 1},
      metagraph=[('drug', 'drug', 'interacts'), ('drug', 'disease', 'treats')])

In [73]:
g.nodes['drug'].data['hv'] = torch.zeros(3, 1)
g.nodes['disease'].data['hv'] = torch.ones(3, 1)
g.edges['interacts'].data['he'] = torch.zeros(2, 1)
g.edges['treats'].data['he'] = torch.zeros(1, 2)

In [76]:
g.ndata

defaultdict(<class 'dict'>, {'hv': {'disease': tensor([[1.],
        [1.],
        [1.]]), 'drug': tensor([[0.],
        [0.],
        [0.]])}})

In [77]:
g.edata

defaultdict(<class 'dict'>, {'he': {('drug', 'interacts', 'drug'): tensor([[0.],
        [0.]]), ('drug', 'treats', 'disease'): tensor([[0., 0.]])}})

In [78]:
hg = dgl.to_homogeneous(g)

In [80]:
hg.ndata

{'_ID': tensor([0, 1, 2, 0, 1, 2]), '_TYPE': tensor([0, 0, 0, 1, 1, 1])}

In [82]:
hg = dgl.to_homogeneous(g,ndata=['hv'])

In [83]:
hg.ndata

{'hv': tensor([[1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.]]), '_ID': tensor([0, 1, 2, 0, 1, 2]), '_TYPE': tensor([0, 0, 0, 1, 1, 1])}

In [84]:
g.ntypes

['disease', 'drug']

In [85]:
hg.ndata[dgl.NTYPE]

tensor([0, 0, 0, 1, 1, 1])

In [86]:
hg.ndata[dgl.NID]

tensor([0, 1, 2, 0, 1, 2])